### ISSUE TITLE
number input should optionally have math expression support

### ISSUE THREAD

**Issue by WebFreak001** [Dechcaudron/dli#2]
So people can write things like `1/3` or `1920-256`. Though you should use an existing package for this instead of making your own imo

**Comment by Dechcaudron** [comment]
Heh, guess what. Turns out I already coded [a package for this](https://github.com/Dechcaudron/ArithEval) back in July 2016. But I'm not terribly sure dli should support this. Can you try to convince me with a sensible use case?

**Comment by WebFreak001** [comment]
`Enter Object Width:`

**Comment by Dechcaudron** [comment]
Or area/volume. Fair enough, will provide.

**Comment by Dechcaudron** [comment]
Well, it took a while to get my old library up to speed and fix some nasty issues, but the feature is now in place. Sadly I cannot reference a specific commit since I've been dealing with some other stuff as well.
